### ISSUE TITLE
Target Audience?

### ISSUE THREAD

**Issue by schae234** [mozillascience/studyGroup#31]
Hi all!

Poll time! :tada: 

I was wondering who everyones audiences were in your own respective study groups? I ask this because I feel (in our own group) we have a competing interest for building community vs reaching new audiences. 

In organizing meet ups for our own study group, I have tried to allow group input on how we should spend our meeting time together. My goal here is to primarily organize with the hope that interesting topics will be threshed out organically. More of an interest group than a study group.

This is vague! It also exacerbates the competing interests I mentioned above. I'd like to focus on things that are interesting to people who have been attending (~5 people) but would also like to incorporate more people. I'd also like to minimize evangelizing and 'recruitment'. 

So who comes to your study groups? How big are they and how many newcomers do you have vs regular members? How often do you meet? How do you 'advertise'?
### Here are my own answers (UMN Hackey Hour):
- We meeting every ~1.5 weeks
- Our study group is mainly members of our laboratory and the laboratory next door. 
- We have around 10 unique visitors who have ever attended a study group
- We have 4-5 regular members who have been to the vast majority of meetings
- All but one of our members are graduate students (we have one brilliant undergrad ;)
- I've sent out email to the plant biology graduate student mailing list and also the biomedical informatics and computational biology mailing list (my home program).

**Comment by noamross** [comment]
Davis R Users Group:
-  Beginner and intermediate users, campus-wide, primarily graduate students and postdocs in the biological and social sciences
-  Meet once per week, 2 hour sessions
-  Every other week there's a 1 hour presentation.  Rest of time is co-working / one-on-one help.
  -   Probably only ~5 people are there every week, 20-25 are people who come about once per month and then others once or twice per semester (when a topic interests them or they have a specific problem to fix).  Attendance fluctuates from 10-30.
  -  Topics range from general (plotting, reproducible documents) to specific (how to use a specific statistical package). Latter tend to be more popular.
-  Also have a regular help e-mail listserv (~400 people, 10-20% who are active users)
-  Advertise the semi-weekly topics on the listserv, e-mail the graduate community as a whole twice per year.

**Comment by tomhohenstein** [comment]
Great question! And I look forward to hearing everyone's response. 

We are just getting going here at BU. Our first session is this week, which is a hacky hour with the goal of generating lesson ideas / meeting times. I've spent most of my initial efforts finding as many grad list-servs as possible and reaching out to student groups - like SAGE, WISE, and the Graduate Government. You might try connecting with a student group on campus to co-sponsor an event.

**Comment by schae234** [comment]
@noamross, Excellent! :+1: How many presenters do you have? Do you cycle through? Are the topics following some sort of pattern or are they chosen each time?

We have a similar group that is part tutorial and part one-on-one sessions. They meet and follow chapters in the book [Bioinformatics Data Skills](http://shop.oreilly.com/product/0636920030157.do) by your very own Vince Buffalo (also at UC Davis). Do you feel like you have a split audience? Scientists who either feel they are completely lost or are super bored? 

I've gotten some feedback from people I've asked in person to come that they are afraid of sharing code or are intimidated to coming to a "coding" event because they aren't programmers. (Whatever that means, I usually tell them it's not "elegent" hour, its hackey hour ;) Even if they don't gain anything else from participating, they have at least shared code through github or sort or broken that first barrier for contributing openly in terms of code.

@tomhohenstein, nice! :metal: We also follow the 'hackey hour' model! One of the ideas that I think has been useful for Hackey hours is having several little or no-prep sessions where you talk ad-hoc about a package or some code that you have found useful. This does **not** mean the sessions aren't quality or useful! I've found that for many (good) packages, we are not able to create a lesson/tutorial better than their own documentation or tutorials. 

For example, last time we talked about [GitLFS](https://git-lfs.github.com/) and just talked about why you would want to use it and what problem it solved. They already have some tutorials and good documentation as well as a github page. I think the little/no prep theory also reduces the activation barrier and is more inviting (we have all been to journal clubs or equivalent where we haven't read the paper and feel guilty). People who are interested in the topic can spend the saved effort by following up on interesting topics **after** the session.

Let us know how the first couple go! Would love to hear how things are in BU.

**Comment by noamross** [comment]
We have 1 presenter every other week, though 2 people have presented together a couple of times.  I poll people on topics they are interested in at the beginning of the quarter, than ask who can teach the topics.  But really there's no plan: you're at the mercy the presenter's schedules and interests.  You can see a collection of talks we've had [here](http://www.noamross.net/davis-r-users-group.html#d-rug-tutorials-from-our-meetings).

I don't think there's generally a split audience.  The core regulars know enough to understand most topics, and the less-regulars come to see topics that they are motivated to learn.

People don't really come to D-RUG because they are interested in programming at all, and we never bill ourselves as a place to learn "computing" or "programming".  Nobody at D-RUG is a primarily programmer and most don't consider themselves bioinformaticians or anything of the sort.  Most attendees need to make THAT graph or run THIS statistical test, and need to fill in the gaps in their knowledge to get there.  Calling ourselves an "R" group caters to this perspective, though it limits our scope somewhat.  Git and Github and code sharing isn't really central to our teaching, though many members pick it up along the way.

**Comment by mbonsma** [comment]
**UofT Scientific Coders (started June 2015):**

Our group is set up to cater to as broad an audience as possible. We don't focus on one particular language or even on programming only: we also talk about general best practices for research (i.e. version control, academic writing, reproducibility).
- Who comes: graduate students from across campus, a few postdocs. The group is very diverse, split across life sciences, natural science, and humanities.
- Size of group, newcomers vs. regulars: between 10 and 30 people come to events, and every week at least a few people come who've never come before (between 1 and 10). There are about 5 'Python' regulars and 5 'R' regulars. We've had a lot of new people the past two weeks because of a recent advertising push. I think about a third are first-year graduate students, the rest are at later stages.
- We meet once per week at a fixed day and time, generally alternating between 1-hour tutorials and coworking sessions.
- Advertising / outreach: at the beginning of the term we contacted all departments in the university and asked them to send out an announcement about the group, we also post occasionally to the weekly grad student newsletter. We have an email list with ~150 people where I send weekly announcements about upcoming events. 

Regarding split audience phenomenon: a lot of more advanced group members seem to enjoy helping beginners, which is really effective at coworking sessions.

**Comment by auremoser** [comment]
This is a great poll, and thank you everyone for contributing. These responses are definitely similar to the Gitter intros that we're now pinging Study Groups to create in our [Mozilla Science SG Gitter Chat](https://gitter.im/mozillascience/studyGroup), feel free to hop in there and learn more from our distributed community, and thanks so much for your responses here!
